version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    volumes:
      - ./:/app
    command: ["go", "run", "src/cmd/main.go"]
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=${POSTGRES_DB:-postgres}
    depends_on:
      - db
    networks:
      - app_network

  db:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
